import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/compnents/ui/Header";
import BreadCrumb from "@/compnents/ui/BreadCrumb";
import Footer from "@/compnents/ui/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "HAES (HAES armenia)",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        <div className="p-[16px] min-h-[calc(100vh-375px)]">
          <BreadCrumb />
          <div className="content">{children}</div>
        </div>
        <Footer />
      </body>
    </html>
  );
}
